"""
Common utilities for Deep Learning: Foundations and Concepts (Bishop & Bishop 2024).
"""
from . import linear_models
from . import decision_theory
from . import bias_variance
from . import exercises_ch4
from . import discriminant_functions
from . import classification_decision_theory
from . import generative_classifiers
from . import discriminative_classifiers
from . import exercises_ch5
from . import limitations_of_fixed_basis_functions
from . import basis_limitations
from . import multilayer_networks
from . import deep_networks
from . import error_functions
from . import mixture_density
from . import exercises_ch6
from . import error_surfaces
from . import gradient_descent
from . import convergence
from . import normalization
from . import exercises_ch7
from . import evaluation_of_gradients
from . import automatic_differentiation
from . import exercises_ch8
from . import inductive_bias
from . import weight_decay
from . import learning_curves
from . import parameter_sharing
from . import residual_connections
from . import model_averaging
from . import exercises_ch9
from . import computer_vision
from . import convolutional_filters
from . import visualizing_cnn
from . import object_detection
from . import image_segmentation
from . import style_transfer
from . import exercises_ch10
from . import graphical_models
from . import conditional_independence
from . import sequence_models
from . import exercises_ch11
from . import attention
from . import natural_language
from . import transformer_language_models
from . import multimodal_transformers
from . import exercises_ch12
from . import machine_learning_on_graphs
from . import neural_message_passing
from . import general_graph_networks
from . import exercises_ch13
from . import basic_sampling
from . import markov_chain_monte_carlo
from . import langevin_sampling
from . import exercises_ch14
from . import kmeans_clustering
